import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";
import { cookies } from "next/headers"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cs = await cookies()
  const theme = cs.get('theme') || { name: "theme", value: "light"}
  return (
    <html lang="zh" data-theme={theme?.value} suppressHydrationWarning>
      <body
      >
        <ThemeProvider initTheme={theme?.value || "light"}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
