import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"
import { ThemeProvider } from "@/context/ThemeProvider";
import { cookies } from "next/headers"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cs = await cookies()
  const theme = cs.get('theme') || { name: "theme", value: "light"}
  return (
    <html lang="zh" data-theme={theme?.value} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider initTheme={theme?.value || "light"}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
