# 使用官方 Node.js 的基础镜像，选择适合的版本
FROM node:20

# 设置工作目录
WORKDIR /app

# 复制项目文件到工作目录
COPY . .

# 安装依赖
RUN npm install

# 构建Next.js应用
RUN npm run build

# 设置环境变量
ENV NODE_ENV production

# 暴露端口
EXPOSE 3000

# 运行应用
CMD ["npm", "start"]
